version: '3.8'

services:
  django:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root@1234
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_ENABLE_PASSWORD_RECOVERY: 'True'
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:5050"
